name: Feature Request
description: Suggest a new feature for NSTG
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Target Package
      description: Which package should this feature be added to?
      options:
        - "@nstg/core"
        - "@nstg/cli"
        - "@nstg/vscode"
        - "@nstg/smt-solver"
        - "New package"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or other helpful context
    validations:
      required: false
